version: '3.8'
services:
  mongo:
    build: .
    image: mongo
    container_name: mongodb
    hostname: mongodb
    networks:
      - mongonet
    ports:
      - "27017:27107"
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=admin
      - MONGO_INIT_DB_ROOT_PASSWORD=adminpassword
    command: --config /etc/mongod.conf

networks:
  mongonet: { }